import React from 'react'
import Head from "next/head";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";

export default function page() {
  return (
    <>
         <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <GoTop />

        <Footer />
    </>
  )
}
