import React from 'react'
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";

export default function page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />  

      <div className="flex bg-white  pt-20 md:pt-[10px]">
        <div className="flex flex-row w-full">
          <div className="flex flex-1 flex-col items-center justify-center relative">
            <div className="flex flex-1 flex-col pb-20  max-w-md md:max-w-2xl ">
              <section className="w-full mx-auto mt-2 md:mt-10 px-5 ">
                <h5 className="font-semibold md:font-bold text-2xl md:text-3xl text-center ">
                  Contact
                </h5>
                <p className=" mt-4 text-xl font-semibold text-gray-700">
                  Now&amp;Me is a safe space for people, from all walks of life,
                  to take their <i>“first step”</i> towards accepting their
                  feelings and talking about them.
                </p>
                <article className="mx-auto mt-10 prose-previewify">
                  
                  <p className="text-2xl">
                    <strong>Address</strong>
                  </p>
                  <ul className="py-4">
                    <li>2208 Hillrise Ave</li>
                    <li>Elizabethton, TN 37643</li>
                    <li>USA</li>
                  </ul>
                </article>
              </section>
            </div>
            
          </div>
        </div>
      </div>

      <div
        class="max-w-screen-xl mt-0 px-8 grid gap-8 grid-cols-1 md:grid-cols-2 md:px-12 lg:px-16 xl:px-32 py-16 mx-auto bg-gray-100 text-gray-900 rounded-lg shadow-lg">
        <div class="flex flex-col justify-between">
          <div>
            <h2 class="text-4xl lg:text-5xl font-bold leading-tight">Lets talk about everything!</h2>
            <div class="text-gray-700 mt-8">
              Hate forms? Send us an <span class="underline">email</span> instead.
            </div>
          </div>
          <div class="mt-8 text-center">
            
          </div>
        </div>
        <div class="">
          <div>
            <span class="uppercase text-sm text-gray-600 font-bold">Full Name</span>
            <input class="w-full bg-gray-300 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="text" placeholder="" />
          </div>
          <div class="mt-8">
            <span class="uppercase text-sm text-gray-600 font-bold">Email</span>
            <input class="w-full bg-gray-300 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
              type="text" />
          </div>
          <div class="mt-8">
            <span class="uppercase text-sm text-gray-600 font-bold">Message</span>
            <textarea
              class="w-full h-32 bg-gray-300 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"></textarea>
          </div>
          <div class="mt-8">
            <button
              class="uppercase text-sm font-bold tracking-wide bg-indigo-500 text-gray-100 p-3 rounded-lg w-full focus:outline-none focus:shadow-outline">
              Send Message
            </button>
          </div>
        </div>
      </div>

      <Footer />
    </>
  )
}
