import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import GoTop from "@/app/components/GoTop";
import CategoryNav from "../components/CategoryNav";
import ArticleHome from "../components/ArticleHome";

import article1 from "@/assets/blogs/article1.png";
import article2 from "@/assets/blogs/article2.png";
import article3 from "@/assets/blogs/victoria.png";
import article4 from "@/assets/blogs/article4.png";
import article5 from "@/assets/blogs/article5.png";



import news from "@/assets/news/news.png"
import news1 from "@/assets/news/news1.png"
import news4 from "@/assets/news/news4.png"
import news5 from "@/assets/news/news5.png"
import news6 from "@/assets/news/news6.png"
import news7 from "@/assets/news/news7.png"
import news8 from "@/assets/news/news8.png"
import news9 from "@/assets/news/news9.png"
import news10 from "@/assets/news/news10.png"
import news11 from "@/assets/news/news11.png"
import news12 from "@/assets/news/news12.png"
import news13 from "@/assets/news/news13.png"
import TipsHome from "../components/TipsHome";


export default function Articles() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <div className="bg-white">
        <div className="dark:bg-transparent">
          <div className="mx-auto flex flex-col items-center py-12 sm:py-12">
            <div className="w-11/12 sm:w-2/3 lg:flex justify-center items-center flex-col mb-5 sm:mb-10">
              <h1 className="text-4xl md:text-4xl lg:text-4xl text-center text-gray-900 font-bold leading-10">
                Beauty
              </h1>
              <p className="mt-7  lg:w-10/12 text-gray-900  font-normal text-center text-[18px] ">
                Find celebrity beauty secrets, hairstyles, skin care tips, and
                beauty trends. Find new ideas for your hair, makeup, nails and
                more.
              </p>
            </div>
          </div>
        </div>
      </div>

      <CategoryNav />

      <div className="flex bg-white">
        <div className="mx-auto flex w-11/12  items-center2 divide-x py-12 sm:py-12">
          <div className="w-3/12 flex flex-col px-2 items-center space-y-4">
            <div className="flex flex-col space-y-1 items-center">
              <div>
                <Image src={article1} alt="" className="objcet-cover" />
              </div>
              <div className="px-0 py-1 pb-4 flex flex-col space-y-3 leading-tight">
                <span className="text-sm text-[#ee0028] font-semibold">Makeup</span>
                <h3 className="font-bold text-base md:text-2xl text-[#333333] leading-tight hover:underline underline-offset-2">
                  <Link href="/detail">
                    12 Eyebrow Growth Serums That Actually Work, According to
                    Experts
                  </Link>
                </h3>{" "}
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-semibold text-[#757575]">
                    By Brigitt Earley
                  </p>
                  <span className="text-xs text-gray-900">January 6, 2024</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col space-y-1 items-center">
              <div>
                <Image src={article2} alt="" className="objcet-cover" />
              </div>
              <div className="px-0 py-1 pb-4 flex flex-col space-y-3 leading-tight">
                <span className="text-sm text-[#ee0028] font-semibold">Wellness</span>
                <h3 className="font-bold text-base md:text-2xl text-[#333333] leading-tight hover:underline underline-offset-2">
                  <Link href="/detail">
                  The Daily Habit That Nutritionists Say Can Drastically Improve Your Health
                  </Link>
                </h3>{" "}
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-semibold text-[#757575]">
                    By Brigitt Earley
                  </p>
                  <span className="text-xs text-gray-900">January 6, 2024</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-6/12 px-2 items-center justify-center">
            <div className="flex flex-col space-y-1 items-center ">
              <div>
                <Image src={article3} alt="" className="objcet-cover" />
              </div>
              <div className="px-0 py-1 pb-4 flex flex-col space-y-3 leading-tight">
                <span className="text-sm text-[#ee0028] font-semibold">Celebrity Beauty</span>
                <h3 className="font-bold text-base md:text-4xl text-[#333333] leading-tight hover:underline underline-offset-2">
                  <Link href="/detail">
                  The Daily Habit That Nutritionists Say Can Drastically Improve Your Health
                  </Link>
                </h3>{" "}
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-semibold text-[#757575]">
                    By Brigitt Earley
                  </p>
                  <span className="text-xs text-gray-900">January 6, 2024</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-3/12 flex flex-col px-2 items-center space-y-4">
          <div className="flex flex-col space-y-1 items-center ">
              <div>
                <Image src={article4} alt="" className="objcet-cover" />
              </div>
              <div className="px-0 py-1 pb-4 flex flex-col space-y-3 leading-tight">
                <span className="text-sm text-[#ee0028] font-semibold">New Ink</span>
                <h3 className="font-bold text-base md:text-2xl text-[#333333] leading-tight hover:underline underline-offset-2">
                  <Link href="/detail">
                  Tattoo Trends 2024: Which Designs Are In and Which Are Out?
                  </Link>
                </h3>{" "}
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-semibold text-[#757575]">
                    By Brigitt Earley
                  </p>
                  <span className="text-xs text-gray-900">January 6, 2024</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col space-y-1 items-center ">
              <div>
                <Image src={article5} alt="" className="objcet-cover" />
              </div>
              <div className="px-0 py-1 pb-4 flex flex-col space-y-3 leading-tight">
                <span className="text-sm text-[#ee0028] font-semibold">Nail it</span>
                <h3 className="font-bold text-base md:text-2xl text-[#333333] leading-tight hover:underline underline-offset-2">
                  <Link href="/detail">
                  Jennifer Lopez Just Debuted a Manicure That’s Going to Be Huge in 2024
                  </Link>
                </h3>{" "}
                <div className="flex flex-col space-y-1">
                  <p className="text-sm font-semibold text-[#757575]">
                    By Brigitt Earley
                  </p>
                  <span className="text-xs text-gray-900">January 6, 2024</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

<TipsHome />
      <ArticleHome />

      <Footer />
    </>
  );
}
