"use client";

import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import GoTop from "../components/GoTop";
import Header from "../components/Header";
import Footer from "../components/Footer";
// import ProductSlider from "../components/ProductSlider";
// import Review from "../components/Review";
import Guarantee from "../components/Guarantee";
import Breadcrumb from "../components/Breadcrumb";
import ThumbnailProduct from "../components/ThumbnailProduct";
import DetailProduct from "../components/DetailProduct";
import Specification from "../components/Specification";
import Recommended from "../components/Recommended";
import NewsFeed from "../components/NewsFeed";
import Ingredient from "../components/Ingredient";

export default function Product() {
  const [count, setCount] = useState(0);

  const handleSubtractOne = () => {
    setCount(count - 1);
  };

  const handleAddOne = () => {
    setCount(count + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <GoTop />

      <NewsFeed />
      <main className=" bg-white">
        <section className="mx-auto max-w-[120rem] w-11/12 md:w-10/12">
          <Breadcrumb />
          <div className="grid-container grid w-full grid-cols-1 gap-3 md:grid-cols-12 xl:gap-4 pt-0 md:pt-1 lg:grid-cols-productDetail lg:pt-6 pb-3 md:pb-10 md:px-3 lg:px-0">
            <ThumbnailProduct />
            <DetailProduct />
            {/* <Specification /> */}
            <Ingredient />
          </div>
        </section>
      </main>

      {/* <Review /> */}
      <Recommended />
      <Guarantee />

      <Footer />
    </>
  );
}
